apiVersion: v1
kind: Service
metadata:
  name: hello-cube-service
  labels:
    app: hello-cube
spec:
  type: LoadBalancer
  selector:
    app: hello-cube
  ports:
    - name: http
      port: 88         # service port (inside cluster)
      targetPort: 5000 # maps to container port
